### ISSUE TITLE
Thoroughly test Nexgen-created files against their GDA equivalents

### ISSUE THREAD

**Issue by dperl-dls** [DiamondLightSource/nexgen#231]
Following the discussion in https://github.com/DiamondLightSource/nexgen/issues/219

We need:
>a system test that compares all the fields, attributes and data types for a Hyperion and GDA nexus file (note there may be some differences that we're fine with but these should be explicitly ignored in the test with a comment as to why it is ok for them to be different

**Comment by DominicOram** [comment]
* We have some tests that compare some parts of these files
* We need to change from just comparing the specific features to compare all of it except the exceptions
* We should have tests for different bit-depths too
* The conclusions of https://github.com/DiamondLightSource/hyperion/issues/1350 will also dictate what we might do here
* Timebox this issue for 2 days to keep writing tests around nexus files, catching as many edge cases found in the above
* Make sure the tests are good documentation of what the edge cases are
