### ISSUE TITLE
Re-enable detector/detectorSpecific external links for EIger

### ISSUE THREAD

**Issue by noemifrisina** [DiamondLightSource/nexgen#236]
Some links in NXdetector and detectorSpecific groups have been disabled because the current data type of the datasets in the `*_meta.h5` does not allow processing (HDF5 will raise an error when trying to convert to ASCII). 
These field should be re-enabled as soon as the datasets are written as strings in the metafile.

This will need to wait for [ADOdin#21](https://github.com/dls-controls/ADOdin/issues/21) to be fixed.

**Comment by DominicOram** [comment]
It seems this was re-enabled in https://github.com/DiamondLightSource/nexgen/pull/256 but then soon disabled again in https://github.com/DiamondLightSource/nexgen/pull/267. The second one looks to me like an accidental bad merge so I will re-enable again
